In [3]:
import numpy as np
np.arange(0, 20, 4) # from 0 (include) until 20 (not included) by 4..

array([ 0,  4,  8, 12, 16])

In [22]:
np.linspace(0, 40, 5) #  .linspace, Returns the number of evenly spaced values between the interval is specified

array([ 0., 10., 20., 30., 40.])

In [29]:
np.random.seed(10)
np.random.rand(2)

array([0.77132064, 0.02075195])

In [32]:
np.zeros(8, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros(8, int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros(8, dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.ones(3, float)

array([1., 1., 1.])

In [62]:
np.random.seed(101)
ranarr = np.random.randint(0, 50, 10)
print(ranarr)

[31 11 17  6 23 11 47  9 13 40]


In [63]:
ranarr.max()

47

In [64]:
ranarr.min()

6

In [65]:
ranarr.argmax()

6

In [66]:
ranarr.argmin()

3

In [67]:
print(np.arange(0,20,4))

[ 0  4  8 12 16]


In [69]:
np.arange(1,5)

array([1, 2, 3, 4])

In [70]:
np.arange(1,5,2)

array([1, 3])

In [71]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [74]:
a = np.array([[1,2], [3,4], [5,6]])

In [75]:
a.ndim

2

In [76]:
a.itemsize

4

In [77]:
a.shape

(3, 2)

In [78]:
a.dtype

dtype('int32')

In [79]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)

In [80]:
a.itemsize

8

In [81]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [82]:
a.shape

(3, 2)

In [83]:
a = np.array([[1,2], [3,4], [5,6]], dtype=complex)

In [84]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
np.ones((3,4), dtype=complex)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [89]:
l = range(5)

In [90]:
l

range(0, 5)

In [91]:
l[0]

0

In [92]:
l[2]

2

In [93]:
np.arange(1,5)

array([1, 2, 3, 4])

In [94]:
np.arange(1, 5, 2)

array([1, 3])

In [95]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [96]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [97]:
np.linspace(1,5,19)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ,
       3.22222222, 3.44444444, 3.66666667, 3.88888889, 4.11111111,
       4.33333333, 4.55555556, 4.77777778, 5.        ])

In [106]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [108]:
a = np.array([[1,2], [3,4], [5,6]], int)

In [109]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
a.shape

(3, 2)

In [111]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [113]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [114]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [115]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
a.min()

1

In [119]:
a.max()

6

In [120]:
a.sum()

21

In [121]:
a.sum(axis=0)

array([ 9, 12])

In [122]:
a.sum(axis=1)

array([ 3,  7, 11])

In [123]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [124]:
np.std(a)

1.707825127659933

In [125]:
a = np.array([[1,2], [3,4]])

In [127]:
b = np.array([[5, 6], [7, 8]])

In [128]:
a

array([[1, 2],
       [3, 4]])

In [129]:
b

array([[5, 6],
       [7, 8]])

In [130]:
a+b

array([[ 6,  8],
       [10, 12]])

In [131]:
a+a

array([[2, 4],
       [6, 8]])

In [132]:
a**a

array([[  1,   4],
       [ 27, 256]], dtype=int32)

In [133]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [134]:
a.dot(b) # BU NE????

array([[19, 22],
       [43, 50]])

In [135]:
b.dot(a) # BU NE????

array([[23, 34],
       [31, 46]])

# NumPy Arrays Basics

In [157]:
np.random.seed(100)
a = np.random.randint(500, size = 10)
a

array([  8, 280, 323, 359, 343,  79, 432, 394, 350, 436])

In [158]:
b = np.random.randint(25000, size = 5)
b

array([10082, 20533, 13890,  7906,  5646])

In [159]:
a.ndim

1

In [161]:
b.shape

(5,)

In [162]:
a.shape

(10,)

In [163]:
c = np.random.randint(10, size = (3,5))
c

array([[2, 1, 0, 8, 4],
       [0, 9, 6, 2, 4],
       [1, 5, 3, 4, 4]])

In [164]:
c.shape

(3, 5)

In [165]:
c.size

15

In [166]:
a.size

10

In [167]:
b.size

5

In [168]:
c.dtype

dtype('int32')

In [169]:
c.itemsize

4

In [170]:
x = np.array([1, 2, 3])
y = np.random.randint(25, size=3)

In [171]:
x

array([1, 2, 3])

In [172]:
y

array([ 3,  7, 17])

In [173]:
np.concatenate([x, y])

array([ 1,  2,  3,  3,  7, 17])

In [183]:
q = np.random.randint(100, size=18)
q

array([94, 19, 98, 63, 53, 27, 56, 30, 48, 47, 39, 38, 44, 18, 64, 56, 34,
       53])

In [189]:
np.split(q, [2, 5]) # ANLAMADIM

[array([94, 19]),
 array([98, 63, 53]),
 array([27, 56, 30, 48, 47, 39, 38, 44, 18, 64, 56, 34, 53])]